### PR TITLE
Implement special command dp

### PR DESCRIPTION
**Pull request by gdevanla**
## Description

Implements \dp command currently supported by psql

## Checklist

- [x] I've added this contribution to the `changelog.rst`.

### CODE REVIEW

**Review by j-bennet — APPROVED** [review]
Very nice. Please add your contribution to changelog, so it can be merged!

**Comment by gdevanla** [comment]
Thanks! Done.

**Comment by mirobertod** [comment]
Hello, do we have an ETA when it will be released on PyPI and then with pgcli?

Thank you

**Comment by j-bennet** [comment]
Good point, it's about time for a new release. I'll get one out.

**Comment by j-bennet** [comment]
1.12.0 is now on pypi:

https://pypi.org/project/pgspecial/1.12.0/

The requirement is not bumped in pgcli yet, but pgspecial can be updated separately with `python -m pip install -U pgspecial`.

**Pull request merged**
