### PR TITLE
Extract pgspecial into an independent package.

### PR DESCRIPTION
**Pull request by j-bennet**

### CODE REVIEW

**Comment by j-bennet** [comment]
@amjith Please review.

**Comment by amjith** [comment]
I'm happy with the changes. Thanks for writing good docs on how to develop/add new commands. 

You should be the author of the package and take care of it going forward. Except for that one recommendation I don't have any objections to merging to master.

**Comment by darikg** [comment]
@j-bennet Is the code coverage thing just on your fork? Can we get that running here?

**Comment by j-bennet** [comment]
I think that for the repo to show up at codecov, @amjith has to log in to https://codecov.io/ using `dbcli` githum login and add it.

**Comment by j-bennet** [comment]
In fact, it's showing up there:

https://codecov.io/github/dbcli/pgspecial

**Comment by amjith** [comment]
I thought I had already enabled it for pgcli. You two should already be admins on the repo, do you not have permissions to enable this?

**Comment by j-bennet** [comment]
@amjith @darikg It is enabled: https://codecov.io/github/dbcli.

**Comment by darikg** [comment]
thank you both!

**Pull request merged**
