### PR TITLE
Support \dE (describe foreign tables)

### PR DESCRIPTION
**Pull request by catherinedevlin**
Added \dE, \dE+, \dE <pattern> support.

## Checklist

- [x] I've added this contribution to the `changelog.rst`.

### CODE REVIEW

**Comment by amjith** [comment]
Thank you for your contribution!! :trophy: 

The tests are passing locally. But they are failing in CI because we don't have permission to create postgres_fdw extension in the CI server's postgres. 

I'm going to merge this PR and then add a skip decorator if we run in CI.

**Comment by j-bennet** [comment]
@amjith 

> The tests are passing locally. But they are failing in CI because we don't have permission to create postgres_fdw extension in the CI server's postgres.

> I'm going to merge this PR and then add a skip decorator if we run in CI.

The tests still fail. They fail locally for me as well:

```
            cur.execute("create server if not exists foreign_db_server "
                        "foreign data wrapper postgres_fdw "
                        "options (host '127.0.0.1', dbname %s )",
>                       (FOREIGN_TEST_DB_NAME, ))
E           psycopg2.ProgrammingError: syntax error at or near "not"
E           LINE 1: create server if not exists foreign_db_server foreign data w...
E                                    ^

tests/dbutils.py:116: ProgrammingError
```

Can you advise how to fix this?

**Comment by amjith** [comment]
@j-bennet I tested this on Postgres10 (haven't tried it on Postgres 9 yet). 

The test requires postgres_fdw extension. I had to run `create extension postgres_fdw` in the database.

**Comment by amjith** [comment]
Actually the test will run `create extension if not exists postgres_fdw` during setup automatically. So I didn't have to do that. But I only tested this in Postgres 10 and above.

**Pull request merged**
