### PR TITLE
Changelog update for 1.4.0.

### PR DESCRIPTION
**Pull request by amjith**
This has to wait till #16 is merged. 

/cc @dbcli/pgcli-core Can you please review?

### CODE REVIEW

**Comment by amjith** [comment]
This is now ready for merge and release. Can I get a thumbs up from the @dbcli/pgcli-core team, if you're satisfied?

**Comment by j-bennet** [comment]
👍

**Comment by darikg** [comment]
:+1:

**Comment by stuartquin** [comment]
:+1:

**Pull request merged**
