### PR TITLE
Fix: "identity" columns not differentiated in \d output

### PR DESCRIPTION
**Pull request by gantsevdenis**
## Description

This fixes https://github.com/dbcli/pgcli/issues/1150
Also:
- `Get column info` now follows more closely the implementation in psql (correct version numbers and columns depending on them)
- Columns are addressed by name instead of their positions (why not using `cursor_factory=DictCursor` in `psycopg2.connect` ?) 
- Removed some semi-colons at the end of lines and useless parenthesis like `if (...)`

## Checklist

- [x] I've added this contribution to the `changelog.rst`.

### CODE REVIEW

**Comment by Dowwie** [comment]
@j-bennet any chance of merging this and releasing an update?  This is approaching two months pending

**Comment by j-bennet** [comment]
Released 1.11.10.

**Comment by Dowwie** [comment]
@j-bennet thank you!  incredible response time.

**Comment by j-bennet** [comment]
You can update pgspecial separately (`pip install -U pgspecial`).

**Comment by Dowwie** [comment]
works!  *thank you*

**Pull request merged**
