### PR TITLE
Updated changelog to release 1.9.0.

### PR DESCRIPTION
**Pull request by j-bennet**
## Description

Changelog update to release 1.9.0.

## Checklist

- ~[ ] I've added this contribution to the `changelog.rst`~.

### CODE REVIEW

**Comment by amjith** [comment]
👍

**Comment by j-bennet** [comment]
@czchen, I see you're listed as a maintainer for https://packages.debian.org/stretch/python-pgspecial, and the latest is 1.7.0. Could you update the package in the debian repo?

**Comment by czchen** [comment]
@j-bennet , I just upload version 1.9.0 to Debian sid, thanks for the reminder.

**Comment by j-bennet** [comment]
@czchen Thanks a lot! 🎉

**Pull request merged**
