### PR TITLE
Update manifest to include license in source distribution

### PR DESCRIPTION
**Pull request by mariusvniekerk**
## Description
As part of creating conda-forge packages for pgcli and pgspecial we should include the license in
the source distribution.

## Checklist

- [ ] I've added this contribution to the `changelog.rst`.

### CODE REVIEW

**Comment by amjith** [comment]
Thank you for including the license files. Happy to merge. 

Tangential question: I thought conda could install regular python packages without any modifications. Is that not true?

**Comment by mariusvniekerk** [comment]
So it certainly can, however for licenses that require distributing the license files it's preferable to have them as part of the source tarball that is on pypi.

**Comment by amjith** [comment]
>  for licenses that require distributing the license files it's preferable to have them as part of the source tarball that is on pypi.

Yes. You're correct about including the licenses file. I was just wondering about conda because you mentioned that this change was required especially for building a conda-forge package.

**Comment by mariusvniekerk** [comment]
mostly because the conda forge maintainers ask nicely :P

**Pull request merged**
