### PR TITLE
Add special cases for postgres < 9 (redshift)

### PR DESCRIPTION
**Pull request by timcleaver**
Here are some changes to make the \ commands work ("works for me") against postgres < 9 and in particular against AWS redshift.

### CODE REVIEW

**Comment by amjith** [comment]
@darikg Would you please do the honors? If you're swamped let me know.

**Comment by darikg** [comment]
Hi @timcleaver I'm glad you're working on this. It looks like you fixed
  - list_roles \du
  - list_functions \df
  - list_datatypes \dT

Are the other ones working for you? On my version of postgres 8.4 it looks like describe table doesn't work:

```
postgres> create table test (x int, y int);
CREATE TABLE
postgres> \d test;
column c.reloftype does not exist
LINE 5:                 CASE WHEN c.reloftype = 0 THEN ''
                                  ^
```

**Comment by timcleaver** [comment]
Yes, sorry. I am new to postgres/redshift so didn't know \d (I missed just \d in the pgcli autocomplete drop-down. I thought everything was 2 letters. It wasn't until I googled further and saw \d+ that I realized it was missing. It appears to do the same as \d). I haven't gotten to that one yet. I hope to get to it over the next few days. Let me know if I missed any others that are fully supported for 9+

**Comment by timcleaver** [comment]
Okay, I have added support for \d. I had to default some values as I couldn't find anything in the documentation to enable me to replicate some of the features of 9.5 that are being relied on (column collation and index backed constraints come to mind). Also, the version check may not be 100% accurate as it appears that some of the functionality relied upon is only 9.5. Some of the queries marked as > 9 might not work on 9.0->9.4.

**Comment by darikg** [comment]
I think some default values are fine since we're just aiming for pg8 soft support. Which features did you find are 9.5 only?

One last problem with `\d`. On it's own it lists tables fine but it should also accept a pattern argument:

```
postgres> \d
+----------+--------+--------+----------+
| Schema   | Name   | Type   | Owner    |
|----------+--------+--------+----------|
| public   | test   | table  | postgres |
+----------+--------+--------+----------+
SELECT
postgres> \d t*
column c.reltriggers does not exist
LINE 5:                     c.reltriggers > 0 AS relhastriggers,
                            ^

postgres>
```

**Comment by timcleaver** [comment]
Some of the features that are defaulted out include:
- relation persistence (pg_class.relpersistence)
- typed table details (pg_class.reloftype)
- column collation (pg_collation)
- index validity (pg_index.indisvalid)
- index backed constraint information
- knowing which triggers are internal (pg_trigger.tgisinternal)

I will admit my testing is not authoritative as my environment probably does not use all the features that would trigger all of the conditional SQL to run. Additionally, many of the version checks are approximate. I did not check every one to be sure 90000 is the exact version to condition all of the SQL on. The issue you identified was one such case where the change landed in 8.4 not 9. Others may even be >9 but <9.5.

I have pushed a fix for the exact issue raised and an additional one I uncovered using a different database.

**Comment by darikg** [comment]
Thanks for looking into this further. I tried again and ran into the same error on postgres 8.4. I looked into it and `cur.connection.server_version` was reported as 80417. So I think the test value in the if-clause should be `>= 80400` not `>= 84000`. Does that make sense?

**Comment by timcleaver** [comment]
Yes, you are quite right. Didn't pay sufficient attention to http://initd.org/psycopg/docs/connection.html#connection.server_version

I believe that 84000 only occurs in that one instance.

**Comment by darikg** [comment]
Ok, I made that small tweak and then merged this in manually. Thanks again

**Pull request closed without merging**
