### PR TITLE
Fix \d on tables with exclusion constraint

### PR DESCRIPTION
**Pull request by lelit**
The description of the index created by an EXCLUDE constraint is missing a space.

### CODE REVIEW

**Comment by j-bennet** [comment]
@lelit How did the output of `\d` look before this fix (example)?

**Comment by lelit** [comment]
Something like:
```
Indexes:
    "resources_pkey" PRIMARY KEY, btree (id)
....
    "resources_discriminator_validity_excl"EXCLUDE USING gist ((discriminator::text) WITH =, validity WITH &&)
Check constraints:
...
```

See, no space before `EXCLUDE`.

**Comment by j-bennet** [comment]
👍

**Comment by j-bennet** [comment]
@lelit Could you add the fix to changelog as well?

**Comment by lelit** [comment]
Sure, will do ASAP, and will try to remember to do that next time 😄

**Pull request merged**
