### PR TITLE
Skip FDW tests in CI.

### PR DESCRIPTION
**Pull request by amjith**
## Checklist

- [ ] I've added this contribution to the `changelog.rst`.

### CODE REVIEW

**Comment by amjith** [comment]
I've run black on the files and it is still failing on pep8 linting errors. Can one of your remind me how to fix this? 

@j-bennet @tsroten

**Comment by j-bennet** [comment]
`black !== pep8`. It is a subset of pep8, but it's a subset that we can consider "good enough". In my PR to apply black to pgcli code (https://github.com/dbcli/pgcli/pull/1049), I completely removed the pep8radius checker from travis.

**Comment by tsroten** [comment]
It looks like all the things pep8radius was complaining about are related to line length. Black uses 88 as the character limit for lines. I wonder if we can just update [pep8radius's arguments](https://github.com/dbcli/pgspecial/blob/master/.travis.yml#L19) to include ` --max-line-length 88`.

**Comment by amjith** [comment]
I'm not gonna do the 80 chars thing. I'm gonna let `black` lead the way going forward.

**Comment by j-bennet** [comment]
@amjith I rebased your branch, it can be merged now. I don't remember, why did we need to skip these tests in CI?

P.S. I also fixed connecting to db in CI. Looks like we were skipping all dbtests because of this problem. Yikes.

**Pull request merged**
