### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by amjith**
## Description
Routine update to the setup.py to cleanup old python versions.

### CODE REVIEW

**Comment by j-bennet** [comment]
pep8. :-/

I think you want to remove them from travis.yml also!

**Comment by amjith** [comment]
Fixed!! :car:

**Comment by j-bennet** [comment]
That pep8 checker sure gave you a lot of trouble.

**Comment by amjith** [comment]
I couldn't run it locally, so it was challenging to get it right.

**Pull request merged**
