### PR TITLE
Stuartquin/help commands

### PR DESCRIPTION
**Pull request by stuartquin**
Hi @j-bennet 

This is a port of https://github.com/dbcli/pgcli/pull/366#issuecomment-143804528 with the docgenerator.py moved into a scripts directory and an accompanying README.

Thanks

### CODE REVIEW

**Comment by j-bennet** [comment]
@stuartquin Still reviewing, but so far looks good. Would you be able to add a unit test to cover the new command?

**Comment by j-bennet** [comment]
@stuartquin So I noticed some commands are present in `\h` (without arguments) that probably should not be there. Here is what pgcli gives me:

```
+---------------------------+----------------------+-----------------------+-----------------------------+----------------------------+-------------------------+
| ABORT                     | ALLFILES             | ALTER AGGREGATE       | ALTER COLLATION             | ALTER CONVERSION           | ALTER DATABASE          |
| ALTER DEFAULT PRIVILEGES  | ALTER DOMAIN         | ALTER EVENT TRIGGER   | ALTER EXTENSION             | ALTER FOREIGN DATA WRAPPER | ALTER FOREIGN TABLE     |
| ALTER FUNCTION            | ALTER GROUP          | ALTER INDEX           | ALTER LANGUAGE              | ALTER LARGE OBJECT         | ALTER MATERIALIZED VIEW |
| ALTER OPCLASS             | ALTER OPERATOR       | ALTER OPFAMILY        | ALTER POLICY                | ALTER ROLE                 | ALTER RULE              |
| ALTER SCHEMA              | ALTER SEQUENCE       | ALTER SERVER          | ALTER SYSTEM                | ALTER TABLE                | ALTER TABLESPACE        |
| ALTER TRIGGER             | ALTER TSCONFIG       | ALTER TSDICTIONARY    | ALTER TSPARSER              | ALTER TSTEMPLATE           | ALTER TYPE              |
| ALTER USER                | ALTER USER MAPPING   | ALTER VIEW            | ANALYZE                     | BEGIN                      | CHECKPOINT              |
| CLOSE                     | CLUSTER              | CLUSTERDB             | COMMENT                     | COMMIT                     | COMMIT PREPARED         |
| COPY                      | CREATE AGGREGATE     | CREATE CAST           | CREATE COLLATION            | CREATE CONVERSION          | CREATE DATABASE         |
| CREATE DOMAIN             | CREATE EVENT TRIGGER | CREATE EXTENSION      | CREATE FOREIGN DATA WRAPPER | CREATE FOREIGN TABLE       | CREATE FUNCTION         |
| CREATE GROUP              | CREATE INDEX         | CREATE LANGUAGE       | CREATE MATERIALIZED VIEW    | CREATE OPCLASS             | CREATE OPERATOR         |
| CREATE OPFAMILY           | CREATE POLICY        | CREATE ROLE           | CREATE RULE                 | CREATE SCHEMA              | CREATE SEQUENCE         |
| CREATE SERVER             | CREATE TABLE         | CREATE TABLE AS       | CREATE TABLESPACE           | CREATE TRANSFORM           | CREATE TRIGGER          |
| CREATE TSCONFIG           | CREATE TSDICTIONARY  | CREATE TSPARSER       | CREATE TSTEMPLATE           | CREATE TYPE                | CREATE USER             |
| CREATE USER MAPPING       | CREATE VIEW          | CREATEDB              | CREATELANG                  | CREATEUSER                 | DEALLOCATE              |
| DECLARE                   | DELETE               | DISCARD               | DO                          | DROP AGGREGATE             | DROP CAST               |
| DROP COLLATION            | DROP CONVERSION      | DROP DATABASE         | DROP DOMAIN                 | DROP EVENT TRIGGER         | DROP EXTENSION          |
| DROP FOREIGN DATA WRAPPER | DROP FOREIGN TABLE   | DROP FUNCTION         | DROP GROUP                  | DROP INDEX                 | DROP LANGUAGE           |
| DROP MATERIALIZED VIEW    | DROP OPCLASS         | DROP OPERATOR         | DROP OPFAMILY               | DROP OWNED                 | DROP POLICY             |
| DROP ROLE                 | DROP RULE            | DROP SCHEMA           | DROP SEQUENCE               | DROP SERVER                | DROP TABLE              |
| DROP TABLESPACE           | DROP TRANSFORM       | DROP TRIGGER          | DROP TSCONFIG               | DROP TSDICTIONARY          | DROP TSPARSER           |
| DROP TSTEMPLATE           | DROP TYPE            | DROP USER             | DROP USER MAPPING           | DROP VIEW                  | DROPDB                  |
| DROPLANG                  | DROPUSER             | ECPG-REF              | END                         | EXECUTE                    | EXPLAIN                 |
| FETCH                     | GRANT                | IMPORT FOREIGN SCHEMA | INITDB                      | INSERT                     | LISTEN                  |
| LOAD                      | LOCK                 | MOVE                  | NOTIFY                      | PG BASEBACKUP              | PG CONFIG-REF           |
| PG CONTROLDATA            | PG CTL-REF           | PG DUMP               | PG DUMPALL                  | PG ISREADY                 | PG RECEIVEXLOG          |
| PG RECVLOGICAL            | PG RESETXLOG         | PG RESTORE            | PG REWIND                   | PG XLOGDUMP                | PGARCHIVECLEANUP        |
| PGBENCH                   | PGTESTFSYNC          | PGTESTTIMING          | PGUPGRADE                   | POSTGRES-REF               | POSTMASTER              |
| PREPARE                   | PREPARE TRANSACTION  | PSQL-REF              | REASSIGN OWNED              | REFRESH MATERIALIZED VIEW  | REINDEX                 |
| REINDEXDB                 | RELEASE SAVEPOINT    | RESET                 | REVOKE                      | ROLLBACK                   | ROLLBACK PREPARED       |
| ROLLBACK TO               | SAVEPOINT            | SECURITY LABEL        | SELECT                      | SELECT INTO                | SET                     |
| SET CONSTRAINTS           | SET ROLE             | SET SESSION AUTH      | SET TRANSACTION             | SHOW                       | START TRANSACTION       |
| TRUNCATE                  | UNLISTEN             | UPDATE                | VACUUM                      | VACUUMDB                   | VALUES                  |
+---------------------------+----------------------+-----------------------+-----------------------------+----------------------------+-------------------------+
```

And here is what psql gives me:

```
Available help:
  ABORT                            ALTER USER MAPPING               CREATE SERVER                    DROP OPERATOR                    PREPARE
  ALTER AGGREGATE                  ALTER VIEW                       CREATE TABLE                     DROP OPERATOR CLASS              PREPARE TRANSACTION
  ALTER COLLATION                  ANALYZE                          CREATE TABLE AS                  DROP OPERATOR FAMILY             REASSIGN OWNED
  ALTER CONVERSION                 BEGIN                            CREATE TABLESPACE                DROP OWNED                       REINDEX
  ALTER DATABASE                   CHECKPOINT                       CREATE TEXT SEARCH CONFIGURATION DROP ROLE                        RELEASE SAVEPOINT
  ALTER DEFAULT PRIVILEGES         CLOSE                            CREATE TEXT SEARCH DICTIONARY    DROP RULE                        RESET
  ALTER DOMAIN                     CLUSTER                          CREATE TEXT SEARCH PARSER        DROP SCHEMA                      REVOKE
  ALTER EXTENSION                  COMMENT                          CREATE TEXT SEARCH TEMPLATE      DROP SEQUENCE                    ROLLBACK
  ALTER FOREIGN DATA WRAPPER       COMMIT                           CREATE TRIGGER                   DROP SERVER                      ROLLBACK PREPARED
  ALTER FOREIGN TABLE              COMMIT PREPARED                  CREATE TYPE                      DROP TABLE                       ROLLBACK TO SAVEPOINT
  ALTER FUNCTION                   COPY                             CREATE USER                      DROP TABLESPACE                  SAVEPOINT
  ALTER GROUP                      CREATE AGGREGATE                 CREATE USER MAPPING              DROP TEXT SEARCH CONFIGURATION   SECURITY LABEL
  ALTER INDEX                      CREATE CAST                      CREATE VIEW                      DROP TEXT SEARCH DICTIONARY      SELECT
  ALTER LANGUAGE                   CREATE COLLATION                 DEALLOCATE                       DROP TEXT SEARCH PARSER          SELECT INTO
  ALTER LARGE OBJECT               CREATE CONVERSION                DECLARE                          DROP TEXT SEARCH TEMPLATE        SET
  ALTER OPERATOR                   CREATE DATABASE                  DELETE                           DROP TRIGGER                     SET CONSTRAINTS
  ALTER OPERATOR CLASS             CREATE DOMAIN                    DISCARD                          DROP TYPE                        SET ROLE
  ALTER OPERATOR FAMILY            CREATE EXTENSION                 DO                               DROP USER                        SET SESSION AUTHORIZATION
  ALTER ROLE                       CREATE FOREIGN DATA WRAPPER      DROP AGGREGATE                   DROP USER MAPPING                SET TRANSACTION
  ALTER SCHEMA                     CREATE FOREIGN TABLE             DROP CAST                        DROP VIEW                        SHOW
  ALTER SEQUENCE                   CREATE FUNCTION                  DROP COLLATION                   END                              START TRANSACTION
  ALTER SERVER                     CREATE GROUP                     DROP CONVERSION                  EXECUTE                          TABLE
  ALTER TABLE                      CREATE INDEX                     DROP DATABASE                    EXPLAIN                          TRUNCATE
  ALTER TABLESPACE                 CREATE LANGUAGE                  DROP DOMAIN                      FETCH                            UNLISTEN
  ALTER TEXT SEARCH CONFIGURATION  CREATE OPERATOR                  DROP EXTENSION                   GRANT                            UPDATE
  ALTER TEXT SEARCH DICTIONARY     CREATE OPERATOR CLASS            DROP FOREIGN DATA WRAPPER        INSERT                           VACUUM
  ALTER TEXT SEARCH PARSER         CREATE OPERATOR FAMILY           DROP FOREIGN TABLE               LISTEN                           VALUES
  ALTER TEXT SEARCH TEMPLATE       CREATE ROLE                      DROP FUNCTION                    LOAD                             WITH
  ALTER TRIGGER                    CREATE RULE                      DROP GROUP                       LOCK                             
  ALTER TYPE                       CREATE SCHEMA                    DROP INDEX                       MOVE                             
  ALTER USER                       CREATE SEQUENCE                  DROP LANGUAGE                    NOTIFY                           
```

Notice how psql does not have PG DUMP, PG RESTORE, REFRESH MATERIALIZED VIEW, and many more. Moreover, if you do `\h PG DUMP` from pgcli, assuming that help is available for that, you'll get an error:

```
vendors> \h PG DUMP
cannot concatenate 'str' and 'NoneType' objects
```

Perhaps there's something in those sgml files that would let us filter out the commands the way psql does it?

**Comment by darikg** [comment]
I think materialized views were added in pg 9.4, so the exact set of commands are going to varying somewhat based on the server version. Agreed that `PG DUMP` etc. don't belong though.

**Comment by darikg** [comment]
We have `\?` described as 'Show help.' and `\h` described as 'Help.'. Maybe expand those to 'Show \special command help' and 'Show SQL syntax help'? Or possibly have both `\?` and `\h` check both special commands and syntax help and act as synonyms?

**Comment by j-bennet** [comment]
@darikg I think expanding command descriptions is better.

**Comment by amjith** [comment]
I like them to be synonyms. So someone can do `\? SELECT` to get help. 

But if they do `\?` it should only display special commands and if they type `\h` it should only display keywords.

**Comment by j-bennet** [comment]
That may be a bit confusing @amjith. I think it's better if they are either synonyms or not, not halfway in between. In psql, they are different commands, so I'd follow the same convention. Also, if someone types `\?` and SELECT is not in the list of suggestions even though it's possible to do `\? SELECT`, it would look like completer does not work as it should.

**Comment by darikg** [comment]
My thought was to make them completely synonymous, to make it as easy as possible for the user to get help, especially since at first glance `\h` and `\?` sound synonymous. But @j-bennet is right that what's suggested after `\h` or `\?` will have a big impact on how the user perceives them. So now I'm not sure.

**Comment by amjith** [comment]
I should have explained my reasoning better. 

When the user types `\?<enter>` we list all the special commands and when they type `\h<enter>` we list all the keywords because that is what the user is familiar with.

But when they type `\? SELECT` we display the help message for `SELECT` statement because that's what they meant. It is easy to forget which one does what and accidentally type `\? SELECT` instead of `\h SELECT`. 

I've done this many times. 

There are some user interfaces (such as python repl) which does this: 

```
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>>
```

I hate this. Because to me it feels like it is passive aggressive UX design. It's trying to say, I know what you meant, but I'm NOT going to do what you asked me to do, instead I'm going to teach you my way of doing things. 

What we're designing is a proactive UX design. We volunteer useful information that is context sensitive. Which should extend beyond just completion. The whole app should be proactive about helping the user. 

That's why I said when a user types `\? SELECT` we know what they meant, so let's do it for them. 

Also I'm not opposed to the idea of suggesting keywords after the `\? `, as long as it is ranked below the special commands. 

I hope that gives you enough context on why I suggested what I suggested.

**Comment by j-bennet** [comment]
Good reasoning @amjith. Yes, we want pgcli to be more helpful than psql, not "just as helpful". I definitely support that.

What if we:

* Suggest meta-commands and then (lower-ranked) keywords when user types in `\? `
* Suggest keywords and then (lower-ranked) meta-commands when user types in `\h `
* Update description for `\?` to "Show SQL syntax or commands help"
* Update description for `\h` to "Show commands or SQL syntax help"

This way, `\h` and `\?` are synonyms but are not exactly the same. An ex-psql user would still see what he expects to see when typing in `\?` or `\h` without parameters. And suggestions would not look broken.

**Comment by amjith** [comment]
Yes. That is a great summary. I'll be happy with that approach.

**Comment by j-bennet** [comment]
@stuartquin On the subject of unit test - do you need any help with that?

**Comment by stuartquin** [comment]
Hi @j-bennet turns out a lot of the weirder Postgres commands were missing either description or synopsis entries in their SGML files so I've omitted these from the listing and updated the script, think it's taken care of the issues.

Also added a couple of unit tests. For the `\h select` test I'm only verifying that the response starts with 'Description', this is in an attempt to make the tests more durable as the actual content of the listing may change in future.

In terms of the `\h`/`\?` aliasing, are we happy to go with what's been proposed above - https://github.com/dbcli/pgspecial/pull/2#issuecomment-144276162

**Comment by darikg** [comment]
> In terms of the \h/\? aliasing, are we happy to go with what's been proposed above - #2 (comment) ?

:+1:

**Comment by j-bennet** [comment]
@stuartquin Yes for aliasing.

**Comment by stuartquin** [comment]
I've updated the description of the 2 commands but I'm a bit hesitant to jump into the aliasing.
As far as I can tell it will require a modification to the way we handle all special commands. 

Currently the special command handlers return a set of rows and an optional message, in the aliasing case we'd need to return 2 sets of rows, each with a different header count.

It's certainly possible but I'm not sure it's worth the changes?

**Comment by darikg** [comment]
What I was suggesting wasn't returning two sets of output, just guessing what the user 'really' wanted and returning that.

Currently:
- `\h` lists available syntax help topics
- `\h <pattern>` lists help for syntax matching `<pattern>`
- `\?` lists available special commands
- `\? <pattern>` ignores the `<pattern>` argument, and lists available special commands

So my only suggestion is to interpret `\? <pattern>` as if the user had typed `\h <pattern>`.

**Comment by j-bennet** [comment]
+1 to what @darikg said. And for autocompletion, we want to suggest both special commands and completions for `\h <space>` and `\? <space>`, to make both `\h pattern` and `\? pattern` synonyms.

**Comment by darikg** [comment]
I don't think we support extended special command help yet. Like ideally `\? \n` would print extended documentation on named queries or whatever, but since it's not implemented yet that would be grounds for a separate PR/feature

**Comment by stuartquin** [comment]
I've aliased `\? SELECT` to `\h SELECT` etc. 
I think this makes the most sense and doesn't require drastic changes.

**Comment by darikg** [comment]
Thanks @stuartquin! lgtm

**Comment by j-bennet** [comment]
Looks good. I think I would add one more test: for every command returned by `\h`, verify that help is available - a sanity check for the script generating our help file.

**Comment by stuartquin** [comment]
Added some quick tests to cover all `\h COMMAND` entries and the aliasing

**Comment by j-bennet** [comment]
Thank you for adding the tests @stuartquin. I think this PR is good to merge, what do you think @darikg ?

**Comment by darikg** [comment]
Yeah do it!

**Comment by j-bennet** [comment]
Good work @stuartquin . :+1:

**Comment by amjith** [comment]
:clap: 

Well done!

**Pull request merged**
